In [7]:
import torch
import numpy as np

# creiamo un tensore da un array
new_tensor = torch.Tensor([[1, 2], [3, 4]])

# creiamo un tensore 2x3 con valori random
empty_tensor = torch.Tensor(2, 3)

# creiamo un tensore 2x3 con valori random -1 e 1
uniform_tensor = torch.Tensor(2, 3).uniform_(-1, 1)

# creiamo un tensore 2x3 con valori random distribuiti nell'intervallo [0, 1)
rand_tensor = torch.rand(2, 3)

# creiamo un tensore 2x3 con valori a zero
zero_tensor = torch.zeros(2, 3)

In [3]:
new_tensor = torch.Tensor([[1, 2], [3, 4]])

# rimpiazzo un elemento alla posizione 0, 0
new_tensor[0][0] = 5
print(new_tensor)

# leggo l'elemento alla posizione 1, 0
print(new_tensor[1][0])           # tensor([ 3.])
# per ottenere lo scalare va usata la funzione item
print(new_tensor[1][0].item())    # 3.


## esempi di slicing
slice_tensor = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# elements from every row, first column
print(slice_tensor[:, 0])         # tensor([ 1.,  4.,  7.])
# elements from every row, last column
print(slice_tensor[:, -1])        # tensor([ 3.,  6.,  9.])
# all elements on the second row
print(slice_tensor[2, :])         # tensor([ 4.,  5.,  6.])
# all elements from first two rows
print(slice_tensor[:2, :])        # tensor([[ 1.,  2.,  3.], [ 4.,  5.,  6.]])

tensor([[5., 2.],
        [3., 4.]])
tensor(3.)
3.0
tensor([1., 4., 7.])
tensor([3., 6., 9.])
tensor([7., 8., 9.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
new_tensor = torch.Tensor([[1, 2], [3, 4]])

# ottengo il tipo del tensore
print(new_tensor.type())   # 'torch.FloatTensor'

# ottendo le dimensioni del tensore
print(new_tensor.shape)    # torch.Size([2, 2])
print(new_tensor.size())   # torch.Size([2, 2])

# ritorna il numero di dimensioni del tensore in questo caso essendo una matrice ne escono 2
print(new_tensor.dim())    # 2

torch.FloatTensor
torch.Size([2, 2])
torch.Size([2, 2])
2


In [5]:
# per fare il reshape del tensore
reshape_tensor = torch.Tensor([[1, 2], [3, 4]])
reshape_tensor.view(1,4)   # tensor([[ 1.,  2.,  3.,  4.]])
reshape_tensor.view(4,1)   # tensor([[ 1.],[ 2.],[ 3.],[ 4.]])

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [9]:
#integrazione tra numpy e pytorch
np_ndarray = np.random.randn(2,2)
# NumPy ndarray to PyTorch tensor
to_tensor = torch.from_numpy(np_ndarray)
# PyTorch tensor to NumPy array
to_ndarray = to_tensor.numpy()

Operazioni tra tensori

In [11]:
my_tensor = torch.Tensor([[1, 2], [3, 4]])

# regular transpose function
my_tensor.t()
# transpose via permute function
my_tensor.permute(-1,0)

tensor_1 = torch.randn(3, 3)
tensor_2 = torch.randn(3, 3)
cross_prod = tensor_1.cross(tensor_2)

maxtrix_prod = tensor_1.mm(tensor_2)

In [12]:
if torch.cuda.is_available():
    print("Scheda video presente")
else:
    print("Scheda video NON presente")

Scheda video NON presente


In [13]:
if torch.cuda.is_available():
    tensor_1 = tensor_1.cuda()
    tensor_2 = tensor_2.cuda()
    tensor_1 + tensor_2